# workflow.yml from external testing repository for testing reusable action (valentinkm/MinervasMemo@dev) in other repositories
name: Process and Summarize VTT File - Map Reduce

on:
  push:
    paths:
      - 'docs_mr/**/*.vtt'

jobs:
  process_and_summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Process VTT files
        uses: valentinkm/MinervasMemo@openai-api
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          public-key: ${{ secrets.PUBLIC_KEY }}
          secret-key: ${{ secrets.SECRET_KEY }}
