name: Process and Summarize VTT File - Map Reduce

on:
  push:
    paths:
      - 'docs_mr/**/*.vtt' 

jobs:
  process_and_summarize:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker- # The prefix for restore-keys to fetch previous caches if the exact key is not found
      
      - name: Process VTT files
        uses: valentinkm/MinervasMemo@dev
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          public-key: ${{ secrets.PUBLIC_KEY }}
          secret-key: ${{ secrets.SECRET_KEY }}
